#%RAML 1.0 Trait
responses:
  400:
    description: Please limit owners to or Sub-merchant can never act as super for any merchant.
  403:
    description: User not authorized to perform this action.
  404:
    description: UserTokenDetails missing.
  500:
    description: Encryption Failed